"""Run every data-health check and render the defect log.

`DEFECT_LOG.md` is generated from `health.json`, never hand-written, so the log can't drift
from what the code actually detected.
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

import orjson

from finagent.config import ROOT, Settings
from finagent.domain.coa_tree import CoaTree
from finagent.domain.models import HEALTH_SEVERITY_RANK, HealthFinding
from finagent.ingest import loaders
from finagent.ingest.fx import RateBook
from finagent.ingest.health_checks import ALL_CHECKS
from finagent.ingest.health_checks.base import AuditContext

FILE_ORDER = [
    loaders.TB_FILE,
    loaders.COA_FILE,
    loaders.PRIOR_TB_FILE,
    loaders.FX_FILE,
    loaders.ADJ_FILE,
]
FILE_LABELS = {
    loaders.TB_FILE: "Trial balance",
    loaders.COA_FILE: "Chart of accounts",
    loaders.PRIOR_TB_FILE: "Prior-period TB",
    loaders.FX_FILE: "FX rates",
    loaders.ADJ_FILE: "Adjustments batch",
}
PIPE_ESCAPED = r"\|"  # a literal pipe inside a markdown table cell
# The assignment brief's own defect table: TB 3, COA 2, adjustments 3, prior TB 1, FX 1.
BRIEF_LISTED = {
    loaders.TB_FILE: 3,
    loaders.COA_FILE: 2,
    loaders.ADJ_FILE: 3,
    loaders.PRIOR_TB_FILE: 1,
    loaders.FX_FILE: 1,
}


def build_context(settings: Settings, inputs: Path | None = None) -> AuditContext:
    base = inputs or loaders.INPUTS
    coa_accounts = loaders.load_coa(base / loaders.COA_FILE)
    fx_rates = loaders.load_fx(base / loaders.FX_FILE)
    raw = loaders.load_adjustments_raw(base / loaders.ADJ_FILE)
    return AuditContext(
        settings=settings,
        coa_accounts=coa_accounts,
        coa=CoaTree(coa_accounts),
        tb_rows=loaders.load_tb(base / loaders.TB_FILE),
        prior_rows=loaders.load_prior_tb(base / loaders.PRIOR_TB_FILE),
        fx_rates=fx_rates,
        ratebook=RateBook(fx_rates, settings.fx.missing_rate_policy, settings.functional_currency),
        entries=loaders.load_adjustments(base / loaders.ADJ_FILE),
        adjustments_raw=raw,
    )


def sort_findings(findings: list[HealthFinding]) -> list[HealthFinding]:
    def key(f: HealthFinding) -> tuple[int, int, str]:
        file_pos = FILE_ORDER.index(f.file) if f.file in FILE_ORDER else len(FILE_ORDER)
        return (file_pos, HEALTH_SEVERITY_RANK[f.severity], f.id)

    return sorted(findings, key=key)


def run_checks(ctx: AuditContext) -> list[HealthFinding]:
    findings: list[HealthFinding] = []
    for module in ALL_CHECKS:
        check: Callable[[AuditContext], list[HealthFinding]] = module.check
        findings.extend(check(ctx))
    return sort_findings(findings)


def health_json(findings: list[HealthFinding]) -> bytes:
    payload = [f.model_dump(mode="json") for f in findings]
    return orjson.dumps(payload, option=orjson.OPT_INDENT_2 | orjson.OPT_SORT_KEYS)


def _evidence_cell(f: HealthFinding) -> str:
    text = orjson.dumps(f.evidence, option=orjson.OPT_SORT_KEYS).decode()
    return text.replace("|", PIPE_ESCAPED)


def render_defect_log(findings: list[HealthFinding], settings: Settings) -> str:
    by_file: dict[str, list[HealthFinding]] = {}
    for f in findings:
        by_file.setdefault(f.file, []).append(f)
    brief_total = sum(BRIEF_LISTED.values())
    critical = sum(1 for f in findings if f.severity == "CRITICAL")
    out = [
        "# Data health — defect log",
        "",
        "*Generated by `finagent audit` from `output/health.json`. Do not edit by hand.*",
        "",
        f"**Listed in the brief: {brief_total} · found by this audit: {len(findings)}** "
        f"({critical} critical, {len(by_file)} files affected). "
        f"FX policy in effect: `{settings.fx.missing_rate_policy}`.",
        "",
        "| File | Listed in brief | Found |",
        "|---|---:|---:|",
    ]
    for file in FILE_ORDER:
        found = len(by_file.get(file, []))
        out.append(f"| {FILE_LABELS[file]} (`{file}`) | {BRIEF_LISTED.get(file, 0)} | {found} |")
    for file in FILE_ORDER:
        items = by_file.get(file)
        if not items:
            continue
        out += [
            "",
            f"## {FILE_LABELS[file]} — `{file}`",
            "",
            "| ID | Severity | Title | Detail | Policy / assumption |",
            "|---|---|---|---|---|",
        ]
        for f in items:
            policy = " · ".join(
                p
                for p in (f.policy_applied, f"assumption {f.assumption}" if f.assumption else "")
                if p
            )
            msg = f.message.replace("|", PIPE_ESCAPED)
            out.append(f"| {f.id} | {f.severity} | {f.title} | {msg} | {policy} |")
        out += ["", "<details><summary>Evidence</summary>", ""]
        for f in items:
            out.append(f"- **{f.id}**: `{_evidence_cell(f)}`")
        out += ["", "</details>"]
    out.append("")
    return "\n".join(out)


def write_audit(
    findings: list[HealthFinding], settings: Settings, out_dir: Path | None = None
) -> tuple[Path, Path]:
    target = out_dir or ROOT / "output"
    target.mkdir(parents=True, exist_ok=True)
    json_path = target / "health.json"
    md_path = target / "DEFECT_LOG.md"
    json_path.write_bytes(health_json(findings))
    md_path.write_text(render_defect_log(findings, settings), encoding="utf-8", newline="\n")
    return json_path, md_path


def run_audit(settings: Settings, out_dir: Path | None = None) -> list[HealthFinding]:
    findings = run_checks(build_context(settings))
    write_audit(findings, settings, out_dir)
    return findings
